name = "deploymulligan"
main = ".open-next/worker.js"
compatibility_date = "2025-11-24"

[compatibility_flags]
nodejs_compat = true

[assets]
directory = ".open-next/assets"

[[routes]]
pattern = "https://www.themulligan.org/*"
